# Do not edit this file. It is tangled from
# Link on your $PATH. In my case it's
# ln -s /home/schmudde/.local/bin
#!/bin/sh
if [ "$#" -eq 0 ]
then
     echo "Starting an Emacs client ..." >&2
     emacsclient -nw
fi

#!/bin/sh
if [ "$#" -eq 0 ]
then
    echo "Starting new Emacs process ..." >&2
    emacs -nw
elif emacsclient -nw "$@" 2> /dev/null
then
    echo "Opened $@ in Emacs server" >&2
else
    echo "Opening $@ in a new Emacs process ..." >&2
    emacs -nw "$@"
fi
